### ISSUE TITLE
(DS) tBTC - color palette

### ISSUE THREAD

**Issue by mikedvii** [keep-network/tbtc-dapp#135]
UpdAte react library to include up to date brand colors, to be documented in Storybook:

Primary:
#5AE680
#370C5F
#469BFF
#AC6E16
#000000

Secondary:
#FFD0C4
#C8F5C5
#C5DCF5
#D2A5FF

Greys:
#4C4C4C
#C4C4C4
#E6E6E6
#F9F9F9

<img width="608" alt="Screen Shot 2019-11-06 at 10 57 25 AM" src="https://user-images.githubusercontent.com/42547342/68320420-8b8ac800-0085-11ea-85ea-de590f854d97.png">

**Comment by Gluzman** [comment]
@mhluongo are you able to close / remove? this isn't happening.
