### ISSUE TITLE
tBTC FAQs page

### ISSUE THREAD

**Issue by mikedvii** [keep-network/tbtc-dapp#138]
Add FAQs page to tbtc.network, design files here: https://www.figma.com/file/wSIaVX0Dh9IJDGMrfGZILd/tBTC-dApps?node-id=1738%3A465

Up to date copy here: https://docs.google.com/document/d/1Ltk5zqmbzzmE9FOnHzlNxJ86PwVfrBTUrgx0vitxhGs/edit?pli=1#heading=h.t6y2lg15ta0e

<img width="1090" alt="Screen Shot 2019-11-06 at 11 22 12 AM" src="https://user-images.githubusercontent.com/42547342/68321694-c7bf2800-0087-11ea-9907-e57f771e4cca.png">

**Comment by mhluongo** [comment]
Closed by https://github.com/keep-network/tbtc-website/pull/32
