### ISSUE TITLE
Include the git revision linked GitHub on the page

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc-dapp#199]
Including a revision in the footer is good UX practice in dApps, and makes bug reports way easier to reproduce. Extra points for linking to Github

**Comment by Gluzman** [comment]
<img width="878" alt="Screen Shot 2020-08-05 at 13 34 45" src="https://user-images.githubusercontent.com/7621557/89444907-6fa17900-d720-11ea-9af3-fa67a209a4ac.png">

did this get implemented? @ironng

**Comment by ironng** [comment]
@Gluzman Yes, implemented in #319!

**Comment by Shadowfiend** [comment]
Technology willing, this should be going out today.

**Comment by mhluongo** [comment]
Closed by #319
