### ISSUE TITLE
The button "View your transaction" not clickable in the step 6/6 of the redeem operation

### ISSUE THREAD

**Issue by k0kk0k** [keep-network/tbtc-dapp#207]
On the step 6 click `View your transaction` button does nothing:
https://dapp.test.tbtc.network/redeem

**Comment by Shadowfiend** [comment]
@ironng assigning this to you, but we may need to check in on what's going on here before you can pick it up. I haven't had a chance to dig into it yet.

**Comment by ironng** [comment]
@Shadowfiend It's a [`TODO`](https://github.com/keep-network/tbtc-dapp/blob/master/src/components/redemption/Congratulations.js#L12) 🙈

**Comment by Shadowfiend** [comment]
... Aight aight aight lolol.
