### ISSUE TITLE
tBTC dApp UI/UX - Make it easy to "restart" anywhere in the process 

### ISSUE THREAD

**Issue by creckhow** [keep-network/tbtc-dapp#218]
- [x] Fill in any missing routes in the dApp for better URL history / page reloads
- [x] Handle error state "restarts"

@mhluongo to break out separate UX ticket

**Comment by Gluzman** [comment]
how might we define "restart?"

what might we consider "the beginning?"

is there more than one answer depending on how far a user has progressed?

what are the reasons a user might need to restart?

does restarting also mean canceling?

*note: making it easy to restart at anytime may actually be dangerous/a misnomer if everything is actually going well and theres no reason too. to be more specific, we may determine that a user needs feedback something has gone wrong, and clear directions to resolve.

**Comment by Shadowfiend** [comment]
@Gluzman if you want me + you + @ironng to talk through this a bit on a call, I think I can give a lot more color here.

**Comment by mhluongo** [comment]
We had a long discussion last week, most of which is getting rolled into the post rc.1 dApp revision. @ironng is going to free-hand making sure every step has a URL in the meantime

**Comment by ironng** [comment]
Closed by #225, unless we want to keep this issue to cover UX stuff?
