### ISSUE TITLE
Better warnings around deposits

### ISSUE THREAD

**Issue by creckhow** [keep-network/tbtc-dapp#220]

**Comment by Shadowfiend** [comment]
Any particular warnings this issue intends to cover? Is “better” here about visuals, missing warnings or something else?

**Comment by Gluzman** [comment]
can we close/remove this issue @creckhow @mhluongo ? unless we want to make sure warnings are documented here?

**Comment by mhluongo** [comment]
I think we can close this in favor of the other work. @ironng we basically want to make sure we enumerate and cover as many of these as we can in #219
