### ISSUE TITLE
tBTC dApp IA

### ISSUE THREAD

**Issue by Gluzman** [keep-network/tbtc-dapp#222]
An IA map reference that reflects new UX patterns and features.

@mhluongo FYI working on this to review when you return from PTO.

**Comment by Gluzman** [comment]
![dapp IA](https://user-images.githubusercontent.com/7621557/84965401-d3260780-b0dc-11ea-8e60-b51305e27a98.png)

@Shadowfiend would love to walk you through this at your convenience.

**Comment by mhluongo** [comment]
Interesting. I could probably use a walkthrough of this as well
