### ISSUE TITLE
tbtc dapp - step 2 console log - RPC Error

### ISSUE THREAD

**Issue by chdru** [keep-network/tbtc-dapp#228]
DevTools failed to load SourceMap: Could not load content for chrome-extension://fleenceagaplaefnklabikkmocalkcpo/content-script.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
web3.js:49 netId: 3
chainId: 3
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available {code: -32601, message: "The method undefined does not exist/is not available"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available {code: -32601, message: "The method undefined does not exist/is not available"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available {code: -32601, message: "The method undefined does not exist/is not available"}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
_runReturnHandlersUp @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
c @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
a @ inpage.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
Deposit.js:446 Creating new deposit contract with lot size 1000000 satoshis...
Deposit.js:454 Looking up new deposit with address 0x7564447CaA2155F23a7352565C09793fE90b72eD backed by keep at address 0x0dD61236117c57e8Ad96E1501Fa0f3689ab82ed9...
Deposit.js:1593 Monitoring deposit 0x7564447CaA2155F23a7352565C09793fE90b72eD for transition to ACTIVE.
Deposit.js:1534 Waiting for deposit 0x7564447CaA2155F23a7352565C09793fE90b72eD keep public key...

**Comment by chdru** [comment]
this is on Windows 10, Version 83.0.4103.116

**Comment by Shadowfiend** [comment]
This appears to have been an issue with the formation of the signer group. We're capturing the related work in #281. Thanks for the report!
