### ISSUE TITLE
tBTC. Step 4/5. Error submitting proof.

### ISSUE THREAD

**Issue by Gregg-First** [keep-network/tbtc-dapp#230]
### Description:
An error occurred on step 4 of minting tBTC.

### Expected behavior:
Receiving tBTC.

### Environment details:
OS: Windows 10 pro, version 10.0.18362, 64 bit OS
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), 7.7.9

### Error message
Finally, let’s submit proof to the sidechain and get you your TBTC.
Transaction has been reverted by the EVM: { "blockHash": "0x8c9b5d19e512158a8a9f7ac215dc16f8ef7d903be28027dacb7572cb00862ec0", "blockNumber": 8268040, "contractAddress": null, "cumulativeGasUsed": 243692, "from": "0x181d5724bf70acf927c437526040e1cddd9dde32", "gasUsed": 137346, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0xe10c1c34a973f24fdf864334e0838a3ef4a77a7b", "transactionHash": "0xbf4dc1c204f3afbbb2d6cdd63b456d9026fadf9a7c0a36f07887755ea391df0c", "transactionIndex": 2, "events": {} }

### TNX
https://ropsten.etherscan.io/tx/0xbf4dc1c204f3afbbb2d6cdd63b456d9026fadf9a7c0a36f07887755ea391df0c

### Log

Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available Object
(anonymous) @ inpage.js:1
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at inpage.js:1
    at We (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at e.exports._runReturnHandlersUp (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at c (inpage.js:1)
    at u (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at a (inpage.js:1)
ElectrumClient.js:48 Connecting to electrum server...
client.js:70 You are connected to an ElectrumX 1.15.0 server.
client.js:82 Negotiated version: [ElectrumX 1.15.0,1.4.2]
ElectrumClient.js:321 Received notification for script hash: [10242115c94a5a3f3b2c2c2c92ee61234a9937e571284240e4709c3b5c00165c] with status: [0f96cc7934e35c9b86dd589f6a2bf35f570a1b987b99c4227c91b1ccdd1bc038]
ElectrumClient.js:80 Closing connection to electrum server...
ElectrumClient.js:48 Connecting to electrum server...
client.js:70 You are connected to an ElectrumX 1.15.0 server.
client.js:82 Negotiated version: [ElectrumX 1.15.0,1.4.2]
ElectrumClient.js:529 Registered listener for blockchain.headers.subscribe event
ElectrumClient.js:474 Received notification of a new block at height: [1780361]
ElectrumClient.js:80 Closing connection to electrum server...
ElectrumClient.js:48 Connecting to electrum server...
client.js:70 You are connected to an ElectrumX 1.15.0 server.
client.js:82 Negotiated version: [ElectrumX 1.15.0,1.4.2]
ElectrumClient.js:80 Closing connection to electrum server...
inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (8000029) or always failing transaction Object
(anonymous) @ inpage.js:1
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://iplppiggblloelhoglpmkmbinggcaaoc/app/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Gregg-First** [comment]
https://ropsten.etherscan.io/tx/0xbf4dc1c204f3afbbb2d6cdd63b456d9026fadf9a7c0a36f07887755ea391df0c

**Comment by Shadowfiend** [comment]
Looks like this is the same issue as detailed in [this comment](https://github.com/keep-network/tbtc-dapp/issues/248#issuecomment-663566632), so I'm closing the issue. Thank you for reporting it!
