### ISSUE TITLE
tBTC dapp: MetaMask - RPC Error: The method undefined does not exist/is not available

### ISSUE THREAD

**Issue by VinnyR** [keep-network/tbtc-dapp#232]
### Description:

Before step 1 of the TBTC minting process an error occurs within the console log:

inpage.js:1 MetaMask - RPC Error: The method undefined does not exist/is not available {code: -32601, message: "The method undefined does not exist/is not available"}

The log file is attached.

### Steps to reproduce the behavior:

1. Go to dapp.test.tbtc.network
2. Click deposit (takes you to dapp.test.tbtc.network/deposit)
3. Click “connect to a Wallet” button, then click Metamask, and metamask opens on it’s login page, asking for the metamask password.
4. The error in the console now appears (before logging into metamask)

### Expected behavior:

I did not expect this error message before even having logged into metamask. I don’t believe it is expected or common, since it doesn’t appear on other dapps when metamask is opened to it’s login page.

### Environment details:

OS: Windows 10 Pro, Version 1909, build 18363.900, 64-bit
CPU: x64 based
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 7.7.9

### Additional context:

Console log file is attached
[dapp.test.tbtc.network-1594436204181.log](https://github.com/keep-network/tbtc-dapp/files/4906200/dapp.test.tbtc.network-1594436204181.log)

**Comment by mhluongo** [comment]
@ironng is this a dup of https://github.com/keep-network/tbtc-dapp/issues/227?

**Comment by ironng** [comment]
@mhluongo yes! Closing.
