### ISSUE TITLE
tBTC dapp: MetaMask error - ALERT: Transaction Error. Exception thrown in contract code.

### ISSUE THREAD

**Issue by VinnyR** [keep-network/tbtc-dapp#233]
### Description:

On step 2 (Initiating deposit) of the TBTC minting process an error occurs within the metamask:

ALERT: Transaction Error. Exception thrown in contract code.

The screenshot is attached along with the console log file.

### Steps to reproduce the behavior:

1. Go to dapp.test.tbtc.network
2. Click deposit (takes you to dapp.test.tbtc.network/deposit)
3. Click ‘connect to a Wallet’ button, click metamask, login to metamask
4. Click ‘Connect’ in metamask (when it says “tBTC would like to connect to your account”)
5. On the web page (Step 1/5 - Initiate a deposit), click ‘Begin now’
6. Metamask window now appears, asking to confirm contract interaction, and displays the error message

### Expected behavior:

No metamask error message

### Environment details:

OS: Windows 10 Pro, Version 1909, build 18363.900, 64 bit OS
CPU: x64 based
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 7.7.9

### Additional context:

Please see the attached screenshot and console log file
[dapp.test.tbtc.network-1594437707661.log](https://github.com/keep-network/tbtc-dapp/files/4906213/dapp.test.tbtc.network-1594437707661.log)
[Screenshot](https://user-images.githubusercontent.com/12225305/87215452-7f4ebd00-c32e-11ea-9144-f84c38786e5a.png)

**Comment by ElderOrb** [comment]
Got this too - at the moment app is unusable for me.

**Comment by Shadowfiend** [comment]
I'm closing this as I suspect it was a variation of the issue detailed in [this comment](https://github.com/keep-network/tbtc-dapp/issues/258#issuecomment-663536507). If you run into this again, hopefully we'll get a clearer error message and can work with that. For now, I'm going to close this issue.
