### ISSUE TITLE
Add version information to the interface

### ISSUE THREAD

**Issue by ElderOrb** [keep-network/tbtc-dapp#236]
... or commit hash.

**Comment by mhluongo** [comment]
Agreed, a commit hash or release in the dApp footer would be a huge improvement, and make submitting issues and avoiding duplicated much easier. @ironng might be a candidate for this week?

**Comment by Gluzman** [comment]
<img width="1366" alt="Screen Shot 2020-07-27 at 10 22 11" src="https://user-images.githubusercontent.com/7621557/88553295-1dab7580-cff3-11ea-96f4-cb74f0239030.png">

the number here is totally a placeholder.
