### ISSUE TITLE
Cannot initiate a deposit while processing another deposit

### ISSUE THREAD

**Issue by DaniellMesquita** [keep-network/tbtc-dapp#237]
Actual deposit:
![image](https://user-images.githubusercontent.com/6765277/87258985-648b5e00-c47e-11ea-8516-268171c74fef.png)

Error:
![image](https://user-images.githubusercontent.com/6765277/87258988-6ce39900-c47e-11ea-8183-09431f100865.png)

Console logs:
![image](https://user-images.githubusercontent.com/6765277/87258997-779e2e00-c47e-11ea-9a79-98c112a3b1fc.png)

**Comment by Shadowfiend** [comment]
This issue isn't correct (witness several other issues from folks who were doing multiple deposits at a time successfully). The transaction in question here (https://ropsten.etherscan.io/tx/0x23f0c73e2349d8d8ee747fed3a74ea4fdfa38c79c081435506f2601f45035841) ran out of gas. I'm interested in finding out why that is compared to others, so if you run into any other transactions that run out of gas, please open an issue with the URL, transaction id, etc. I'm going to close this issue for now as we haven't seen issues dealing with parallel deposits that I know of, and the transactions in question don't seem to be affected by parallelism issues.

**Comment by DaniellMesquita** [comment]
@Shadowfiend 

It wasn't out of gas because I had more than enough Ropsten ETH.
