### ISSUE TITLE
Selector for custom deposit lot size

### ISSUE THREAD

**Issue by DaniellMesquita** [keep-network/tbtc-dapp#239]
Should be shipped before the r1, for better testing.

Suggested sizes:
- [ ] 0.01 (current)
- [ ] 0.02
- [ ] 0.05
- [ ] 0.1
- [ ] 0.2
- [ ] 0.5
- [ ] 1
- [ ] 2

Doesn't matter if the mainnet launch will not support all bigger lot sizes, it will be good for full test coverage for when it is implemented.

**Comment by mhluongo** [comment]
Thanks for this @DaniellMesquita! Lot sizes are actually governed by the protocol - you can see the [initial sizes here](https://github.com/keep-network/tbtc/blob/master/solidity/contracts/system/TBTCSystem.sol#L78) and the [governance here](https://github.com/keep-network/tbtc/blob/master/solidity/contracts/system/TBTCSystem.sol#L226).

Closing this in favor of #255, which will go out in the next release.
