### ISSUE TITLE
UX suggestions: Minting Complete behavior / balance dashboard

### ISSUE THREAD

**Issue by VVyvrn** [keep-network/tbtc-dapp#241]
I think user experience would be improved with more information and/or options after Step 5 is complete. For example:

"You may now close this window." 

"Click here to return to tbtc.network."

"Mint again" link to reload the dAPP at step 1. 

"Check my balance" might be a good a future feature that would lead to a dashboard screen which cleanly visualized current values pulled user's metamask (or whatever) wallet address. Obviously users can look for the token in their wallet themselves (or add the token contract manually if needed) or look on etherscan, but for more mainstream adoption, less experienced users might likely to think that they should check it on the dAPP or tbtc.network site. 

For comparison, if you hold tokens in a liquidity pool on balancer, etc., you can pull up a a little dashboard showing your current percentage stake, etc.

Just seeing that number reflected back to you gives users confidence that nothing has gone wrong and their money is right where they expect it to be.

**Comment by Shadowfiend** [comment]
Absolutely. A lot of this is going to be captured in the IA work and new flows that are being tracked in #222. More to come on that front; in the meantime, I'm going to close this issue since we're tracking the underlying work. Thank you for the clear articulation!
