### ISSUE TITLE
RPC Error: gas required exceeds allowance (8000029) or always failing transaction

### ISSUE THREAD

**Issue by VinnyR** [keep-network/tbtc-dapp#244]
### Description:
On step 2 (Initiating deposit) of the TBTC minting process an error message appears within the browser console:

    RPC Error: gas required exceeds allowance (8000029) or always failing transaction

and in MetaMask:

    ALERT: Transaction Error. Exception thrown in contract code.

### Steps to reproduce the behavior:

1. Go to dapp.test.tbtc.network
2. Click deposit (takes you to dapp.test.tbtc.network/deposit)
3. Click ‘connect to a Wallet’ button, click metamask, login to metamask
4. Click ‘Connect’ in metamask (when it says “tBTC would like to connect to your account”)
5. On the web page (Step 1/5 - Initiate a deposit), click ‘Begin now’
6. Metamask window now appears, asking to confirm contract interaction, and displays the error message. This also is when the error message appears in the broswer console (before clicking confirm in MetaMask).

### Environment details:
OS: Windows Ubuntu 18.04.2 LTS 64-bit
Web Browser: Mozilla Firefox 78.0.1 (64-bit)
Wallet: Metamask (Firefox addon), Version 8.0.4

### Screenshots / Files
[console-export-2020-7-13_2-56-20.txt](https://github.com/keep-network/tbtc-dapp/files/4910194/console-export-2020-7-13_2-56-20.txt)

**Comment by Shadowfiend** [comment]
Going to quote from #258, a similar issue:

> Yeah, unfortunately due to some limitations in Metamask, the only way to see the underlying error is to confirm the transaction and see what error it comes back with. Most likely you were trying to open a deposit during some pricing/bond issues we were having on Ropsten last week (see keep-network/keep-ecdsa#504). Closing this issue for now, but please feel free to reopen if you're still seeing something similar.

Thanks for the report!
