### ISSUE TITLE
Error Redeeming Bond: Step 2/6 - "Number can only safely store up to 53 bits"

### ISSUE THREAD

**Issue by VVyvrn** [keep-network/tbtc-dapp#245]
### Description:
Redemption crashes on Step 2/6 while following standard behaviors, throws this message:

Error redeeming bond
We’re waiting for you to confirm invoice details in your Wallet.

Number can only safely store up to 53 bits

https://dapp.test.tbtc.network/deposit/0x3cAf685693B3e029e53D9C0e5EfE35691Cb5eE47/redemption

### Steps to reproduce the behavior:
1)Go to dapp.test.tbtc.network
2)Click redeem (takes you to dapp.test.tbtc.network/redeem)
3) Click ‘connect to a Wallet’ button, click metamask, login to metamask, click ‘Connect’ in metamask
4) User enters a valid TDT ID in first text box, green checkmark appears
5) User enters a valid BTC address in second text box, green checkmark appears
6) Click Redeem

### Expected behavior:
dApp continues to Step 2 without error

### Environment details:
OS: macOS, macOS 10.15.5 (19F101)
Web Browser: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (browser-integrated)

### Screenshots
If applicable, add screenshots to help explain your problem and any console log files.
<img width="1440" alt="Screen Shot 2020-07-12 at 9 04 11 PM" src="https://user-images.githubusercontent.com/68137734/87263926-33ae2780-c484-11ea-8530-86b4bc8224fc.png">
<img width="1440" alt="Screen Shot 2020-07-12 at 9 00 42 PM" src="https://user-images.githubusercontent.com/68137734/87263932-3741ae80-c484-11ea-9354-fb0447dd07bf.png">
[53Bitx.txt](https://github.com/keep-network/tbtc-dapp/files/4910237/53Bitx.txt)

**Comment by Shadowfiend** [comment]
Found the issue here, and captured it as keep-network/tbtc.js#57. Closing this issue in favor of that one.
