### ISSUE TITLE
MetaMask window pops up without prefilled Gas for the transaction

### ISSUE THREAD

**Issue by saltypalo** [keep-network/tbtc-dapp#246]
### Description:
My apologies for lack of information on this issue, since I made a screenshot of this before I was aware of how to properly report bugs. 
MetaMask window pops up without appropriate Gas inputs, so user has to do it himself, it won't be any issue for experienced user, while sometimes could be a bit challenging to choose right numbers for newer users so that transaction will be processed quickly enough.
Translation from RU language: ALERT Gas limit should be at minimum 21000

### Steps to reproduce the behavior:
1. Go to 'https://dapp.test.tbtc.network/deposit'
2. Pass all steps until 4th step
3. See error

### Expected behavior:
MetaMask window pops up with automatically filled in amount of Gas for this exact transaction.

### Environment details:
OS: Windows 10 Home, version 10.0.18362, 64 bit OS
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), 7.7.9

### Screenshots
![Снимок экрана (111)](https://user-images.githubusercontent.com/68163853/87281978-73b0f100-c4fc-11ea-9c70-190df04b21fa.png)

**Comment by Shadowfiend** [comment]
Hmmm… We do a gas estimate on our end, and if that fails we let Metamask give it a shot. I would say this is more likely a Metamask bug than a bug in our dApp.

I'm going to close this issue for now as I don't see a clear way that we would be causing this, but if you see it come up again, please do reopen---especially if you see it happen consistently to a particular deposit or similar.
