### ISSUE TITLE
tBTC dApp: UI/UX Suggestion - Homepage/Back button

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#247]
From my observation, it is needed for tBTC dApp to have home button(back).
It is necessary to have it in case of someone misclick the Deposit button while he is trying to Redeem or vice versa.
Not to mention we might have some more menus in the future, and what should we do if we do not have home button if we want to get back to the home page?

**Comment by Shadowfiend** [comment]
Yep, a lot of this is going to be handled as we roll out the changes to the information architecture outlined in #222. Going to close this issue in the meantime.
