### ISSUE TITLE
Error submitting proof

### ISSUE THREAD

**Issue by bonsfi** [keep-network/tbtc-dapp#248]
### Description:
The bug was both in Metamask transaction after the testnet BTC were sent and also displayed in tBTC dapp.
https://dapp.test.tbtc.network/deposit/0x0f9E4034a637e23A2807Ae0E6ec87c659Bc16eaD/prove
https://ropsten.etherscan.io/tx/0x7b32ea62011700a517c41c09768fb147b908f45ac0a5757e092d6a245a124d08
https://ropsten.etherscan.io/tx/0x0ce9e5b497dca533b4e3fa2249de712b24d9929cb33e46ea94272533b8df7f89

### Steps to reproduce the behavior:
1. Go to https://dapp.test.tbtc.network/
2. Did the standard process with Metamask Ropsten and block.io wallet. And got this error at step 4:
Transaction has been reverted by the EVM: { "blockHash": "0x878a1c0f7e3af94f880a5bbe4a46f9fb2befb7d249bcfe84d7dadf943e5dd309", "blockNumber": 8284740, "contractAddress": null, "cumulativeGasUsed": 149117, "from": "0xb7a764884a2fbcfc7177b5c53a7797ee7ff4bb39", "gasUsed": 128117, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x0f9e4034a637e23a2807ae0e6ec87c659bc16ead", "transactionHash": "0x0ce9e5b497dca533b4e3fa2249de712b24d9929cb33e46ea94272533b8df7f89", "transactionIndex": 1, "events": {} }

### Expected behavior:
Expected my 0.01 testnet BTC to become 0.01 Ropsten tBTC

### Environment details:
OS: macOS catalina
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)  
Wallet: Metamask (Chrome extension), Version 7.7.9

### Screenshots

<img width="695" alt="Screenshot 2020-07-13 at 11 27 20" src="https://user-images.githubusercontent.com/12712595/87288614-e1105200-c4fb-11ea-871f-c5b540f7b425.png">

**Comment by saltypalo** [comment]
Would like to confirm that just received same error on step 4 in following environment:

OS: Windows 10 Home, version 10.0.18362, 64 bit OS
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), 7.7.9

**Comment by culgin** [comment]
Same issue here. 

[https://ropsten.etherscan.io/tx/0xdbd70eb49ed9bc723627bfa2e6588e4c2cf4df7e2607637e0dc91d556f285632](https://ropsten.etherscan.io/tx/0xdbd70eb49ed9bc723627bfa2e6588e4c2cf4df7e2607637e0dc91d556f285632)

![image](https://user-images.githubusercontent.com/68226207/87299244-38cfad00-c53e-11ea-8efa-4bf77a28b3c9.png)

OS: Windows 10 
Web Browser: Firefox, 78.0.2 (64-bit)
Wallet: Metamask (Firefox extension), Version 8.0.4

On-screen error:
Transaction has been reverted by the EVM: { "blockHash": "0x69363ad57f44d0dee0a16e0656f91b4541a9ee1b44dc4e76c26f60f59af547bf", "blockNumber": 8285288, "contractAddress": null, "cumulativeGasUsed": 492982, "from": "0x13e001bbfbe3a699ef48bc9e64139373a9649f30", "gasUsed": 128117, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0x0a910605b93a3d2b80caedc6154eb489c9656ac3", "transactionHash": "0xdbd70eb49ed9bc723627bfa2e6588e4c2cf4df7e2607637e0dc91d556f285632", "transactionIndex": 4, "events": {} }

**Comment by Shadowfiend** [comment]
Thanks for reporting these! The failures look like they're due to difficulty issues on Bitcoin testnet. Unfortunately that's not really under our control---it's one of the downsides of Bitcoin's testnet that difficulty changes more frequently than mainnet, and the way we handle difficulty comparisons for transaction proofs is a bit brittle to that issue.

I'm going to close this as it's not strictly under our control, and I don't expect us to see this issue on mainnet. Because mainnet changes difficulty on a roughly steady schedule that operates on the order of weeks, and the timeouts in our system are on the order of hours, it's not really possible for a transaction proof to become unprovable for this reason on mainnet without the underlying deposit flow having timed out.
