### ISSUE TITLE
tBTC dAppp - step 2/5 Error: [ethjs-rpc] rpc error with payload

### ISSUE THREAD

**Issue by saltypalo** [keep-network/tbtc-dapp#252]
### Description:
Issue appeared in the browser, + transaction in MetaMask has failed. 

Error: [ethjs-rpc] rpc error with payload {"id":2778512727095,"jsonrpc":"2.0","params":["0xf89072843b9aca008318c4f8945536a33ed2d7e055f7f380a78ae9187a3b1d8f75880107924d66383800a4b7947b4000000000000000000000000000000000000000000000000000000000000f424029a0d666b52fa1a45407b75aa52f95450039af8099b41298ec9ae2a1c665c9b320e3a071a7f174b01a088ed1645ba85192ce248d0b0df87487558c397d5d067587da65"],"method":"eth_sendRawTransaction"} [object Object]

### Steps to reproduce the behavior:
1. Go to 'https://dapp.test.tbtc.network/deposit/'
2. Start the minting TBTC process
3.Confirm transaction in MetaMask
4. See error in the step 2

### Expected behavior:
Successful transaction and next step (3/5)

### Environment details:
OS: Windows 10 Home, version 10.0.18362, 64 bit OS
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), 7.7.9

### Additional context:
This is the first time I have encountered this issue, while this is at least my 30+ attempt

### Screenshots
If applicable, add screenshots to help explain your problem and any console log files.
![(126)](https://user-images.githubusercontent.com/68163853/87301634-9bae4d80-c518-11ea-8cfd-b459e280896b.png)

**Comment by VinnyR** [comment]
I seem to get this error whenever I set the gas limit to a higher value than what is automatically set in MetaMask. In particular, it seems to occur whenever the gas limit is set to ~ 8100000 or higher.

My environment:

OS: Windows 10 Pro, Version 1909, build 18363.900, 64 bit OS
CPU: x64 based
Web Browser: Google Chrome, Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 7.7.9

**Comment by Shadowfiend** [comment]
The block gas limit on Ropsten is 8M gas, so trying to set your transaction's limit above that will fail. You can check the latest block on Etherscan at any given moment to see what the current block gas limit is (it's listed under “Gas Limit”). 

Closing this issue as we can't do anything about this particular issue, though I wish Metamask would flag it more clearly.
