### ISSUE TITLE
tBTC dApp shows a blank page on Deposit (Using mobile phone [iOS)

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#254]
### Description:
I was trying to make a deposit using my mobile phone, tBTC dApp shows a complete blank page when I clicked Deposit.

### Steps to reproduce the behavior:
1. Go to https://dapp.test.tbtc.network/
2. Click on Deposit
3. See error

### Expected behavior:
tBTC dApp should direct me to the deposit page like the redeem page.

### Environment details:
OS: iPhone 7 plus, iOS 13.5.1
Web Browser: Safari

### Screenshots
See SS below
![iOS](https://user-images.githubusercontent.com/67586661/87332049-2ddc4300-c565-11ea-9ae0-70bfaa2ab8e8.png)

**Comment by JaviAnibarro** [comment]
wrong place, closed

**Comment by Shadowfiend** [comment]
Have you seen this more than once? This is definitely a new one :grimacing:

**Comment by JaviAnibarro** [comment]
Yes, I just tried it right now.
Everything looks fine until I clicked Deposit button

**Comment by ironng** [comment]
Tested locally. Looks like it's because iOS Safari doesn't support the [web Notification api](https://developer.mozilla.org/en-US/docs/Web/API/notification)

![Screen Shot 2020-07-24 at 5 57 10 PM](https://user-images.githubusercontent.com/1986137/88445420-5969f380-cdd7-11ea-96c2-36ab51c31d3d.png)
