### ISSUE TITLE
New Warning Message Design

### ISSUE THREAD

**Issue by Gluzman** [keep-network/tbtc-dapp#256]
Provide updated VIS style for error and warning messages on RC.1

**Comment by Gluzman** [comment]
<img width="1125" alt="Screen Shot 2020-07-16 at 10 44 05" src="https://user-images.githubusercontent.com/7621557/87685345-48730f80-c751-11ea-9053-84ef8a5e43cd.png">

*note @Shadowfiend and @mhluongo I took a stab at a different written message here in addition to the slightly updated visual design. my goal was to strike a more "caring" tone.

design with original message ↓

<img width="557" alt="Screen Shot 2020-07-16 at 10 47 00" src="https://user-images.githubusercontent.com/7621557/87685696-b15a8780-c751-11ea-8cfc-a0994e08e89a.png">

**Comment by Gluzman** [comment]
@ironng updated the warning message alert for the current dapp here - updated container shape, color, line spacing, and added an warning icon.

**Comment by ironng** [comment]
@Gluzman Thanks for the callout! I'm going to add this to the #264 PR since review hasn't started.

**Comment by Gluzman** [comment]
@Shadowfiend is the 👍for the new or old copy? or just for visual update?

**Comment by Shadowfiend** [comment]
New copy, sorry.
