### ISSUE TITLE
Error Log Export

### ISSUE THREAD

**Issue by Gluzman** [keep-network/tbtc-dapp#257]
Allows user to download an error log from within dapp.

**Comment by Gluzman** [comment]
@mhluongo button is straightforward -- would it make sense to display a warning & number of errors encountered? 
<img width="836" alt="Screen Shot 2020-07-14 at 09 51 12" src="https://user-images.githubusercontent.com/7621557/87433645-8fc59880-c5b7-11ea-814b-e066be03e78f.png">

**Comment by mhluongo** [comment]
Nah, not sure that's even exposed / possible in-browser

**Comment by Gluzman** [comment]
@mhluongo updated:

@ironng pinging you about this update to the dapp footer.

<img width="1563" alt="Screen Shot 2020-07-14 at 11 12 16" src="https://user-images.githubusercontent.com/7621557/87442957-e4224580-c5c2-11ea-9de4-c75006a48d35.png">


<img width="640" alt="Screen Shot 2020-07-14 at 11 06 16" src="https://user-images.githubusercontent.com/7621557/87442278-141d1900-c5c2-11ea-9978-246000b476f1.png">
