### ISSUE TITLE
tBTC dApp step 4 error - Can't mint TBTC with a deposit that isn't in active state

### ISSUE THREAD

**Issue by saltypalo** [keep-network/tbtc-dapp#263]
### Description:
Encountered this issue once, when I started to open multiple browser tabs to mint TBTC. I had 3 tabs on the same step (4) and 2 of them completed TBTC minting, while one was stuck with this issue.
"Can't mint TBTC with a deposit that isn't in active state"

### Steps to reproduce the behavior:
1. Go to 'https://dapp.test.tbtc.network/'
2. Pass all the steps till the last one
3. See error

### Expected behavior:
Completion of the last step

### Environment details:
OS: macOS Mojave 10.14.6 (18G5033)
Web Browser: Google Chrome, 83.0.4103.106 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 8.0.4

### Screenshots
If applicable, add screenshots to help explain your problem and any console log files.
<img width="788" alt="Screen Shot 2020-07-13 at 23 31 33" src="https://user-images.githubusercontent.com/68163853/87473762-aa852500-c62a-11ea-9f6f-a252c6ff40da.png">

**Comment by Shadowfiend** [comment]
This might actually be a chain propagation issue; in particular, it's likely that this deposit advanced to the active state, but when we checked it to make sure that it was indeed in that state, the Ethereum node we connected to was a different one that hadn't received the updated deposit state yet.

This is a tough one; it may require considering a retry mechanism in tbtc.js 🤔

**Comment by saltypalo** [comment]
@Shadowfiend If I encounter this issue once more, I will report back. So far it was only once
