### ISSUE TITLE
Image on dapp.test.tbtc.network is over 17MB - not web friendly

### ISSUE THREAD

**Issue by VinnyR** [keep-network/tbtc-dapp#267]
When visiting dapp.test.tbtc.network, the web browser downloads an image that is over 17MB:

    https://dapp.test.tbtc.network/static/media/Flow.8441ae9a.png

An image of this filesize is not expected for the purposes of this app, which leads me to believe it's something that has been overlooked or yet to be addressed (which would be totally understandable as there are probably higher priority issues at the moment). Anyway, I submit this issue just in case it is something that has been missed or overlooked.

Although it does seem to load asynchronously and doesn't appear to affect the loading of the webapp, a smaller filesize may help the server cope better during times of heavy load / surge usage.

![Annotation 2020-07-15 153216](https://user-images.githubusercontent.com/12225305/87558994-a18b6680-c6b1-11ea-928b-3b66c2059cb3.png)

**Comment by mhluongo** [comment]
It's about to be nuked :) you can follow the visual rework [here](https://github.com/keep-network/tbtc-dapp/pull/264)

**Comment by ironng** [comment]
Image removed in #264
