### ISSUE TITLE
tBTC dApp redeem transaction - testnet BTC tx is not available

### ISSUE THREAD

**Issue by saltypalo** [keep-network/tbtc-dapp#269]
### Description:
Encountered this issue while trying to redeem tBTC for testnet BTC. When trying to see transaction details it's non-existent. 
While transaction itself is happening.

### Steps to reproduce the behavior:
1. Go to 'https://dapp.test.tbtc.network/redeem'
2. Pass steps 1-4
3. Click on "Follow along in block explorer"
4. See that there's no transaction to follow along.

### Expected behavior:
Displaying transaction

### Environment details:
OS: macOS Mojave 10.14.6 (18G5033)
Web Browser: Google Chrome, 83.0.4103.106 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 8.0.4

### Screenshots
<img width="1103" alt="Screen Shot 2020-07-14 at 23 08 57" src="https://user-images.githubusercontent.com/68163853/87583180-3b6c0700-c6e4-11ea-9051-cb2917d3f6e2.png">
<img width="1004" alt="Screen Shot 2020-07-14 at 23 09 20" src="https://user-images.githubusercontent.com/68163853/87583193-3e66f780-c6e4-11ea-9a96-e7742c423ed8.png">

**Comment by Shadowfiend** [comment]
I believe this is fixed as of #225, which was deployed recently. Going to close the issue, but let me know if that's not the case.

Also---please include the dApp URL if you do run into it again. That'll help us track it down. Thanks!
