### ISSUE TITLE
Content overflow in mobile phone [iOS]

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#272]
### Description:
tBTC website does not load properly, almost half of the redeem button is missing when I opened it using mobile phone.

### Steps to reproduce the behavior:
1. Go to https://dapp.test.tbtc.network/
2. See error

### Expected behavior:
An adjusted content based on mobile screen

### Environment details:
OS: iPhone 7 plus, iOS 13.5.1
Web Browser: Safari

### Screenshots

![overflow](https://user-images.githubusercontent.com/67586661/87562275-019cff80-c6e8-11ea-9199-6063c6929ea2.png)

**Comment by Shadowfiend** [comment]
@ironng do you mind poking at this? Feels like we just need to stack the two buttons when we hit the appropriate breakpoint.
