### ISSUE TITLE
Bug with MetaMask browser on Android.

### ISSUE THREAD

**Issue by Gregg-First** [keep-network/tbtc-dapp#273]
### Description:
A bug while using MetaMask browser on Android.
1) First page 'https://dapp.test.tbtc.network/' is displayed incorrect. (screenshot added)
2) Blank screen after clicking "deposit" button. (screenshot added)

### Steps to reproduce the behavior:
1. Open MetaMask browser on Android.
2. Go to 'https://dapp.test.tbtc.network/'
3. See first page.
4. Click on '"deposit' button.
5. See Blank screen.

### Expected behavior:
Step 1/5 is expected 'Initiate a deposit'

### Environment details:
OS: Android 9 PKQ1.181203.001. MIUI 11.0.9.0 (PFHINXM)
Web Browser: MetaMask Browser v0.2.19 (32) 
Wallet: Metamask (Google play app), v0.2.19 (32) 

### Screenshots
![Screenshot_2020-07-16-12-41-11-430_io metamask](https://user-images.githubusercontent.com/47347865/87658681-3307e080-c765-11ea-84cb-df3dd4252510.jpg)
![Screenshot_2020-07-16-12-39-59-867_io metamask](https://user-images.githubusercontent.com/47347865/87658698-3a2eee80-c765-11ea-967e-312a2c452966.jpg)

**Comment by Shadowfiend** [comment]
@Gregg-First could you give this another shot? If it fails, I believe there should be a button to download the error log in the footer---getting that error log would be super useful, though it's possible from the symptoms you're describing that it won't be available.

**Comment by Shadowfiend** [comment]
This may also be related to #262 ...

**Comment by Gregg-First** [comment]
@Shadowfiend I switched off all possible restrictions for metamask app but the result is still the same. Unfortunately there is no opportunity getting that error log.

Also I can confirm the same issue as #262 .

**Comment by Shadowfiend** [comment]
Perfect. We should be getting a release out later this week that we're hoping will fix 262, at which point we can see if it's fixed the issue here as well. 🤞

**Comment by Gregg-First** [comment]
Ok, I will follow and then check this stuff.

**Comment by Gregg-First** [comment]
Problem solved and everything works correctly. @Shadowfiend

**Comment by Shadowfiend** [comment]
🙌❤️🚀
