### ISSUE TITLE
 Not enough operators in pool issue

### ISSUE THREAD

**Issue by bonsfi** [keep-network/tbtc-dapp#276]
I got this error when I tried to mint. 

In my opinion this situation should be explained so that the user understands why the transaction fails.

Also, and very important, when you try to do the transaction, you get a warning message in Metamask but you are still able to proceed with the transaction when I think that a mechanism to avoid proceeding should be implemented. The main reason behind my proposal is because the transaction goes through and the user gets UPSET when he/she sees that the BTC address was not created and he/she paid worthless fees. In mainnet fees are high and this situation will discourage users, causing them to go to other BTC briges.

Please see screenshots:

<img width="354" alt="Screenshot 2020-07-17 at 19 31 30" src="https://user-images.githubusercontent.com/12712595/87814704-86148d00-c864-11ea-907d-c95104808470.png">

<img width="804" alt="Screenshot 2020-07-17 at 19 33 27" src="https://user-images.githubusercontent.com/12712595/87814719-8e6cc800-c864-11ea-9d6c-ea75493450a5.png">

SOLUTION: inform the user that the transaction is not possible and avoid by some mechanism that he/she can start the transaction.

**Comment by jasonchewyl** [comment]
I experienced the same error and feel the same way. 

SOLUTION:
If a transaction is not possible, there should be a notice on the initiate deposit page e.g. Not enough Bonded ETH to make a deposit. You can try again in approx...

**Comment by mhluongo** [comment]
Hey guys, this is on our radar!

**Comment by Shadowfiend** [comment]
Going to track this in #260, as it's a variation on the same set of errors.
