### ISSUE TITLE
UX improvements Redeem TDT - POP UP or similar - Compare to REN

### ISSUE THREAD

**Issue by bonsfi** [keep-network/tbtc-dapp#277]
Please introduce a pop up that asks to connect wallet. Please see Renbridge and how they clearly ask for it at the beggining in as a top priority and they display it at the center of the screen. Please see image below:
<img width="497" alt="Screenshot 2020-07-17 at 19 54 15" src="https://user-images.githubusercontent.com/12712595/87816255-561ab900-c867-11ea-8d23-65f382570617.png">

And compare to Ren:
<img width="795" alt="Screenshot 2020-07-17 at 19 55 18" src="https://user-images.githubusercontent.com/12712595/87816379-7ea2b300-c867-11ea-9512-22b773a395d0.png">

**Comment by mhluongo** [comment]
Thanks for the thought @bonsfi! I strongly disagree with this approach to wallet connections, unfortunately. We'll be rolling out an improved wallet UX, but it won't look like this -- a huge modal that keeps you from seeing what the dApp can do is an anti-pattern and potential privacy concern.
