### ISSUE TITLE
TDT's issued even if we couldn't mint tBTC

### ISSUE THREAD

**Issue by chdru** [keep-network/tbtc-dapp#279]
We are getting TDT's even if we couldn't mint tBTC.

I've tried multiple times to mint tBTC even though most of the times unsuccessful due to contract issues but still got issued with TDT's which are quite confusing.  Of the many times I tried, I was able to succeed 2 times and I was expecting 2 TDT's but I've got 11 TDT's. 

My wallet - 0x27D4876C8dD7abF6e40aAC6F9Fe0942e01fBF5cE

Successful txns hash's - 
0x0935dd5fb0beb6e1a7957660c61c358baafff85ce1f26d0e0c1797e3580ef7d1
0x3bca0a65bdb91ade2c4d4c7ecd24a69dcc9c27cda893b38332d3b2a0683cbc81

![image](https://user-images.githubusercontent.com/68074440/87825828-72a1fb80-c83d-11ea-8c70-6f315d189e52.png)

**Comment by Shadowfiend** [comment]
@mhluongo explained this one in a newer issue, #291. This is expected behavior, however---see that issue for more details.
