### ISSUE TITLE
TDT ID - not obvious where it is displayed

### ISSUE THREAD

**Issue by saltypalo** [keep-network/tbtc-dapp#283]
I know, that this issue was already reported few times and most likely team is aware of that, but it's not quite convenient, that TDT ID of tBTC is actually hash of transaction of the fee and not TDT ERC721 ID. Screenshots below:
<img width="854" alt="Screen Shot 2020-07-19 at 17 41 54" src="https://user-images.githubusercontent.com/68163853/87878145-28f71380-c9eb-11ea-9ed4-a740745647aa.png">
<img width="811" alt="for redeem" src="https://user-images.githubusercontent.com/68163853/87878153-344a3f00-c9eb-11ea-8189-e20f69d7f173.png">

**Comment by Shadowfiend** [comment]
We went back and forth on this. We're mostly focused on removing the TDT id as a necessary thing to keep track of in the first place (via #222).

I'm interested in why you consider it inconvenient to present in this way, though---it may feed into the broader discussion as well.

**Comment by saltypalo** [comment]
@Shadowfiend This is just from ordinary user perspective, who is rarely ever on etherscan. To be honest, I have looked through more transactions on etherscan during 1-2 weeks of TBTC than I went trough previous half a year. But it's pleasant to know, that TDT ID in future won't be needed. Thank you for your response

**Comment by Shadowfiend** [comment]
Sweet, thanks for the extra detail! Going to close this issue since the work to pull the TDT id out altogether is being tracked in 222, but feel free to file any other issues you run into!
