### ISSUE TITLE
this.contract.methods.signerFeeTbtc is not a function

### ISSUE THREAD

**Issue by chdru** [keep-network/tbtc-dapp#289]
Error during deposit in step 2/5- 
this.contract.methods.signerFeeTbtc is not a function

![image](https://user-images.githubusercontent.com/68074440/88329685-f6e9f800-ccef-11ea-9604-7123060304d7.png)

Attached the console logs 
[dapp.test.tbtc.network-1595532196802.log](https://github.com/keep-network/tbtc-dapp/files/4968312/dapp.test.tbtc.network-1595532196802.log)

This is on Windows 10/Chrome browser

**Comment by Shadowfiend** [comment]
Whoops, we deployed a new version of tbtc.js that included keep-network/tbtc.js#53, without deploying the latest version of tbtc that implemented the underlying changes. Pulling this back now. We wanted to get you the latest UI goodness faster, and here we are :wink:

**Comment by Shadowfiend** [comment]
Deploying a fix now, hold tight.

**Comment by Shadowfiend** [comment]
This should be fixed!

**Comment by Shadowfiend** [comment]
If you're still seeing this, please feel free to reopen the issue, btw! Make sure you've reloaded with a clear cache for the dApp though.

**Comment by chdru** [comment]
I was able to get past this error now - Thank you !
