### ISSUE TITLE
Redemption step 6/6 "View your transaction" button have wrong link

### ISSUE THREAD

**Issue by k0kk0k** [keep-network/tbtc-dapp#295]
`View your transaction` button have wrong link
![image](https://user-images.githubusercontent.com/60854664/88411285-57f0f900-cde0-11ea-8683-4b51bf7b0bda.png)

**Comment by Shadowfiend** [comment]
@k0kk0k do you mind sharing a URL here?

**Comment by k0kk0k** [comment]
> @k0kk0k do you mind sharing a URL here?

https://dapp.test.tbtc.network/deposit/0xbDACBDf7c4A4e3B3963524E07eCc0B3EA014a47E/redemption/congratulations

button url: https://etherscan.io/token/null

**Comment by Shadowfiend** [comment]
@ironng would you mind having a look here when you get a chance? Wondering if we just haven't deployed the fix here, or if there's something odd going on.
