### ISSUE TITLE
tBTC dApp stopped after Step 4 (submit proof to the sidechain)

### ISSUE THREAD

**Issue by ninjaboonx** [keep-network/tbtc-dapp#305]
### Description:
Deposit of 1 Testnet BTC to the Dapp hung at Step 4.
On Step 4, 3 TXs were confirmed on the ETH network but the message did not move on to Step 5 of the deposit process.
Kindly find the successful ETH TXs.

https://ropsten.etherscan.io/tx/0xcab012a17f2493d8842c1107a17cda59cd73c014abddb8a1db669010429fa154
https://ropsten.etherscan.io/tx/0x816883d2e78e716942f3e5916fecf0ff1b844ef5d3ab218291b7a28393ff8a4e
https://ropsten.etherscan.io/tx/0xc1964628c7d5b763c0da4ffa64739bf21faf343818f0bfa45aeb49ded4103809

### Steps to reproduce the behavior:
1. Go to 'https://dapp.test.tbtc.network/'
2. Pass all the steps till Step 4. 
3. ETH TX is confirmed.
4. Step 4 message "Finally, let’s submit proof to the sidechain and get you your TBTC." stays stucked on the browser.

### Expected behavior:
Completion of step 4 (out of 5)

### Environment details:
OS: Window 10 Home, Version 10. OS Build 19041.388
Web Browser: Firefox 78.0.2 [(64-bit)](url)
Wallet: Metamask (Chrome extension), Version 8.0.5

![2020-07-26 14_52_57-tBTC](https://user-images.githubusercontent.com/5178741/88473580-9659f580-cf51-11ea-9c5c-af50c5bccbd7.png)

![2020-07-26 14_57_56-Settings](https://user-images.githubusercontent.com/5178741/88473581-98bc4f80-cf51-11ea-8e8e-2d113d712451.png)

**Comment by ramaruro** [comment]
I have experienced the same problem 4 times already, I have 4 TDT tokens, I need to convert them to tBTC (Step 5)

**Comment by ninjaboonx** [comment]
I also have 1 TDT

**Comment by ninjaboonx** [comment]
finally the TX went through https://ropsten.etherscan.io/tx/0x663393de2c1e8196f0c1df45ab1bec6cadebab27427588edfcb4ed8dc162cb5d
