### ISSUE TITLE
Usability: Minting Step 5/5: Change name of "Deposit Address" to "TDT ID" and ask to store it as it is needed for Redemption 

### ISSUE THREAD

**Issue by ramaruro** [keep-network/tbtc-dapp#313]
When you have succesfully minted as in the screenshot below, you should get a message in that screen that the contract is the TDT ID that is required for Redeeming, so it should be stored somewhere to easily remember.
Right now it says "Deposit Address" , but in the Redeem screen (see below) it refers to it as TDT ID.
So two requests:
* Change "Deposit Address" to "TDT ID"
* Add a note to store it as it will be needed for Redeeming

![Deposit Address --> TDT ID](https://user-images.githubusercontent.com/68167410/88554686-6dd30980-cfec-11ea-8cdd-df7033d4031a.png)

![image](https://user-images.githubusercontent.com/68167410/88554272-f0a79480-cfeb-11ea-8596-def11a8723d5.png)

**Comment by Shadowfiend** [comment]
We'd like to eliminate the need to remember this address from the mix altogether; currently that's going into the IA work in #222; we'll post updates and the issues that capture the related work from there.

That said, you're right that in the meantime we should match the terminology on the two sides.
