### ISSUE TITLE
Redeem sometimes do not work

### ISSUE THREAD

**Issue by JaviAnibarro** [keep-network/tbtc-dapp#315]
### Description:
A few days ago I found a problem causing me to not be able to do the redeem. The button does not work and it's stuck at the homepage.

### Steps to reproduce the behavior:
1. Go to https://dapp.test.tbtc.network/
2. Click on Redeem
3. See error

### Expected behavior:
Redeem button should work as intended

### Environment details:
OS: Windows 10 Pro, 64 bit OS  
Web Browser: Google Chrome and Mozilla (64-bit)  
Wallet: Metamask (Chrome extension and Mozilla), Version 7.7.9

### Additional context:
At first, I thought it's a problem with my connection so I decided to not report it, but these few days someone else encountered this problem too. So I assume it's not about my connection, but who knows?

### Screenshots
See screenshot below, you should see _the black Redeem button_, it turned black because I clicked it but it's stuck
![mozila](https://user-images.githubusercontent.com/67586661/88593599-0075b600-d08a-11ea-81b9-a93d7770ff25.png)

**Comment by Shadowfiend** [comment]
@JaviAnibarro I see you closed the issue here---what ended up being the problem?

**Comment by JaviAnibarro** [comment]
@Shadowfiend I think it should be because of the TDT ID but I can not be certain about it because a few days ago when I was able to do the redemption I tried to change TDT ID into differents address based on my transaction but nothing changed, it's stuck like that. But can not test it again after 53-bit issue showed up.

**Comment by Shadowfiend** [comment]
Ok cool, thank you. Hoping to snipe the 53-bit issue this week, but if you see this come up again please feel free to reopen or file a new issue!
