### ISSUE TITLE
What happens to the test Bitcoin if stuck on Step 4?

### ISSUE THREAD

**Issue by jasonchewyl** [keep-network/tbtc-dapp#333]
I got an error on Step 4 - Error submitting proof.

![image](https://user-images.githubusercontent.com/53902721/89244357-d481a400-d638-11ea-8f51-4dd3dfbc1ddc.png)

I have also read the [previous threads](https://github.com/keep-network/tbtc-dapp/issues/248) about how this is an issue on testnet Bitcoin side.

However... 

- what is the solution?
- what happens to my testnet Bitcoin?
- where is it? 
- if I cannot get pass Step 4, what should I do?
- can I get my testnet Bitcoin back? It took a lot of time and effort to accumulate 1 testnet Bitcoin.

**Comment by ramaruro** [comment]
I have the same problem, lost 2 BTC so far due to the same problem: 

https://dapp.test.tbtc.network/deposit/0x55011DA991a3BfBD8a24CfaDdA112755057B7831/prove
https://dapp.test.tbtc.network/deposit/0x67dB4AcE460d323d1ab4c4eF97236D267879DE1D/prove

**Comment by mhluongo** [comment]
> can I get my testnet Bitcoin back? It took a lot of time and effort to accumulate 1 testnet Bitcoin.

Both of you, save the links and proof send them in in the redemption form - we can make sure they're handled on the other side.

**Comment by jasonchewyl** [comment]
Thanks Matt. Will do.
