### ISSUE TITLE
TDT IDs processed internally without need for user to interact with them.

### ISSUE THREAD

**Issue by Ostrovmaria80** [keep-network/tbtc-dapp#335]
This feature was discussed previously in some of branches but I believe it's possible to do some quick fix, so that not only tBTC will be transferred, but also TDT ID ownership and it would be easier to redeem for the new owner.

Example: my friend sent me 0.029 tBTC to practice redeeming: https://ropsten.etherscan.io/tx/0x26ffe0863b8517897d192bb7b3fe4dae723a278141254f52e053f0aedab9d258

And right away I cannot do anything with them, as I don't know TDT IDs for them. So i have to ask him to get TDT ids for every 0.01 that he minted, which is very inconvenient

**Comment by Shadowfiend** [comment]
It's actually a little more complicated than that. You don't need your friend's TDT ids, you need the id(s) of any TDT that is publicly available for redemption (meaning any TDT that has had TBTC minted off of it). If your friend has TBTC, they have already lost ownership of the TDT---that is part of the minting process.

We're covering the overall work to remove TDTs from the dApps language and knowledge requirements in a comprehensive rework of the dApp and its information architecture introduced in #222. Going to close this issue in the meantime, as the work for it will spin off of there.
