### ISSUE TITLE
Can't complete redeem process, with error "No deployment info found for contract TBTCConstants, network ID 1"

### ISSUE THREAD

**Issue by VinnyR** [keep-network/tbtc-dapp#344]
### Description:
I've been trying to redeeem my tBTC for testnet BTC, and it kept getting stuck at step 4/5.

I saved the url and kept trying it every now and then:

`https://dapp.test.tbtc.network/deposit/0xc87D9da83f0A32bE4802e6CE9346a42ce48686b4/redemption/prove`

The app would be stuck at step 4/5, but now when I visit the above url, the app just shows "Loading..." and stays stuck on this screen. The console log shows the error:

```
Uncaught (in promise) Error: No deployment info found for contract TBTCConstants, network ID 1.
    at EthereumHelpers.js:241
    at Object.getDeployedContract (EthereumHelpers.js:248)
    at Deposit.js:266
    at Array.map (<anonymous>)
    at e.<anonymous> (Deposit.js:261)
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:267)
    at Generator.e.<computed> [as next] (runtime.js:103)
    at r (asyncToGenerator.js:3)
    at o (asyncToGenerator.js:25)
```

### Steps to reproduce the behavior:
1. Go to the url `https://dapp.test.tbtc.network/deposit/0xc87D9da83f0A32bE4802e6CE9346a42ce48686b4/redemption/prove` (this was saved from an earlier attempt at redeeming tBTC which got stuck at step 4/5)
2. Connect to MetaMask
3. After a while, it's apparent that the app is stuck here and will not proceed
4. Error appears in the browser's console log.

### Expected behavior:
I assumed I could come back to this url and continue the redeem process from where I left it last time at step 4/5.

### Environment details:
OS: Windows 10 Pro, Version 1909, build 18363.959, 64 bit OS  
Web Browser: Google Chrome, Version 84.0.4147.125 (Official Build) (64-bit)
Wallet: Metamask (Chrome extension), Version 8.0.6

### Additional Info

Testnet BTC TXID: `d83a58da82a1c9ed5049286008986d7865713f96db7cd6d65ebed8a8c2b42853`
TDT ID: `0xc87D9da83f0A32bE4802e6CE9346a42ce48686b4`
Ropsten TXID: `0x9b69e6109b4feb9566b38a576b3eaa29109ba01af4ae4cad1a44f3b60c6d18a8`

### Screenshots and Log Files
[Screenshot](https://user-images.githubusercontent.com/12225305/90185705-015b5700-ddaf-11ea-953e-18da98e3d851.png)
[Browser console log file - dapp.test.tbtc.network-1597351868516.log](https://github.com/keep-network/tbtc-dapp/files/5071373/dapp.test.tbtc.network-1597351868516.log)
[App log file - tbtc-dapp-v0.18.0-rc-log-1597351898202.json.txt](https://github.com/keep-network/tbtc-dapp/files/5071375/tbtc-dapp-v0.18.0-rc-log-1597351898202.json.txt)

**Comment by VinnyR** [comment]
I also seem to get the same error when trying to complete a **deposit** from a previous attempt where I got stuck.

URL: `https://dapp.test.tbtc.network/deposit/0xc2B8565fc9f61424D2ed3638455C0911508Db8c6/prove`
Testnet BTC TXID: `d83a58da82a1c9ed5049286008986d7865713f96db7cd6d65ebed8a8c2b42853`

###Log Files
[Browser console log file - dapp.test.tbtc.network-1597352603521.log](https://github.com/keep-network/tbtc-dapp/files/5071415/dapp.test.tbtc.network-1597352603521.log)
[App log file - tbtc-dapp-v0.18.0-rc-log-1597352607457.json.txt](https://github.com/keep-network/tbtc-dapp/files/5071419/tbtc-dapp-v0.18.0-rc-log-1597352607457.json.txt)

**Comment by Shadowfiend** [comment]
You appear to be trying to use the testnet dApp with your Metamask pointed to mainnet. Right now the dApp doesn't offer a particularly friendly error that this is the case, unfortunately.

If that is indeed the problem, please feel free to close this issue :)

**Comment by VinnyR** [comment]
Thanks for pointing that out, I just confirmed that this was indeed caused by me mistakenly using mainnet instead of ropsten. Oops!
