### ISSUE TITLE
dApp roadmap

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc-dapp#88]
Right now, we have a v1 deposit dApp and are planning a v1 redemption dApp. We know these need to be more tightly integrated in the future, and we know there are many UX improvements in the meantime. Let's get a proper roadmap together for these efforts.

**Comment by Gluzman** [comment]
@mhluongo can we close this one?

**Comment by mhluongo** [comment]
@Michael yeah. For reference we have this [in Figma](https://www.figma.com/file/wSIaVX0Dh9IJDGMrfGZILd/tBTC-dApp?node-id=3302%3A0)
